version: '3'

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    networks:
      - hola-net
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
      - '433:433'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks:
      - hola-net

networks:
  hola-net:

